[project]
name = "worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.121.2",
    "uvicorn>=0.38.0",
    "httpx>=0.27.0",
    "google-genai>=1.57.0",
]

[tool.poe.tasks]
start = "uvicorn main:app --reload"

[dependency-groups]
dev = [
    "poethepoet>=0.37.0",
]
